server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/Real_time_chat_app
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Real-time-chat-app

  servlet:
    multipart:
      max-file-size: 50MB



application:
  file:
    uploads:
      media-output-path: ./uploads

cloudinary:
  cloud-name: diju35umx
  api-key: 126973877632524
  api-secret: Jn81qsBQIs0GBygOQyIwmsj0R0I

#  cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
#  cloudinary.api-key=${CLOUDINARY_API_KEY}
#  cloudinary.api-secret=${CLOUDINARY_API_SECRET}