services:



  postgres:
    container_name: postgres-sql-chat-app
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: Real_time_chat_app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - realtimechatapp
    restart: unless-stopped
  keycloak:
    container_name: keycloak-chat-app
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - realtimechatapp
    command:
      - "start-dev"
    volumes:
      - keycloak_data:/opt/keycloak/data/
    restart: unless-stopped



networks:
  realtimechatapp:
    driver: bridge
volumes:
  postgres:
    driver: local
  keycloak_data:
    driver: local
